server:
  port: 8083

spring:
  application:
    name: demo_web
eureka:
  client:
    fetch-registry: true  #是否从eureka服务器获取各个微服务地址
    register-with-eureka: true #是否注册到eureka服务器
    service-url:
      defaultZone:  http://localhost:8081/eureka/ #2020
feign:
  hystrix:
    enabled: true #开启feign熔断，默认为false